const express=require('express')
const app=express()
const aboutPage=require('./about')
const loginPage=require('./login')
const contactPage=require('./contact')
const servicePage=require('./service')
app.get('/',(req,res)=>{
    res.send("Home Page")
})

app.use("/about",aboutPage)
app.use('/service',servicePage)
app.use('/login',loginPage)
app.use('/contact',contactPage)
app.listen(3600)